import React from "react";
import Layout from "../components/Layout";

const TermsConditions = () => {
  return (
    <Layout>
      <div className="w-full">
        <div className="md:w-[70%] px-4 md:px-0 mx-auto flex flex-col gap-7 py-12">
          <h2 className="text-3xl font-semibold">Terms And Conditions</h2>
          <h3 className="text-2xl font-semibold">TERMS OF USE</h3>
          <div className="flex flex-col gap-4 font-normal text-[15px]">
            <h2>1. GENERAL</h2>
            <p>
              a{")"} This document is an electronic record in terms of
              Information Technology Act, 2000 and rules there under as
              applicable and the amended provisions pertaining to electronic
              records in various statutes as amended by the Information
              Technology Act, 2000. This electronic record is generated by a
              computer system and does not require any physical or digital
              signatures.
            </p>
            <p>
              b) This document is published in accordance with the provisions of
              Rule 3 (1) of the Information Technology (Intermediaries
              guidelines) Rules, 2011 that require publishing the rules and
              regulations, privacy policy and Terms of Use for access or usage
              of www.krishnaayurved.com.
            </p>
            <p>
              c) The domain name www.krishnaayurved.com (“Website”), including
              its online services, such as use of software on Website and
              information, articles , news, blogs and text, graphics, images and
              information obtained from service providers and any other material
              contained on the Website is owned and operated by RAJPUTANA AGRICO
              (“Company”) a Private Company, incorporated under the provisions
              of the Companies Act, 2013, and having its registered office at:
              Daga Building Paota “A” Road Jodhpur, Rajasthan, India where such
              expression shall, unless repugnant to the context thereof, be
              deemed to include its respective representatives, administrators,
              employees, directors, officers, agents and their successors and
              assigns.
            </p>
            <p>
              d) For the purpose of these Terms of Use (“Terms”), wherever the
              context so requires, <br /> i) The term ‘You’ or “User” shall mean
              any legal person or entity accessing using this Website to
              services provided or registered on this Website, who is competent
              to enter into binding contracts, as per the provisions of the
              Indian Contract Act, 1872; <br /> ii) The terms ‘We’, ‘Us’ &‘Our’
              shall mean the Website and/or the Company, as the context so
              requires. <br /> iii) The terms ‘Party’& ‘Parties’ shall
              respectively be used to refer to the User and the Company
              individually and collectively, as the context so requires.
            </p>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default TermsConditions;
